### ISSUE TITLE
After checkout back to card

### ISSUE THREAD

**Issue by AgenturSchroeder** [METMEER/METMEER_CustomerComment#1]
Hi, i have an issu with your "plugin".
I can see the new field in the frontend and in the database.
But if i reach the checkout and click "buy" than the site jumps back to the card view without anny error message.

All works fine untill i use this "plugin".

Is this an error with the new m2.1.3 version?

**Comment by rikwillems** [comment]
Thanks for trying the extension and giving this feedback.
The module was developed on 2.1.2. I just tested a clean install on 2.1.3 and this works fine too. Can you check you deployed the static content properly?
